apiVersion: v1
 kind: Service
 metadata:
   name: fashionrecommender-deployment
 spec:
   type: NodePort
   ports:
   - name: appport
     port: 5000
     targetPort: 5000
     nodePort: 30000
   selector:
     app: fashionrecommender-deployment